name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install pnpm
        run: npm install pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: npx run storybook built

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./storybook-static
          github_token: ${{ secrets.GITHUB_TOKEN }}
